lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  alias BlogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.SetCurrentUser
  end

  pipeline :protected do
    plug :put_layout, {BlogWeb.LayoutView, :protected}
    plug Plugs.EnsureAuthenticated
  end

  pipeline :feed do
    plug :accepts, ["xml"]
  end

  scope "/", BlogWeb do
    pipe_through [:browser]

    get "/", PortfolioController, :index
    get "/blog", BlogController, :index
    get "/blog/:titled_slug", BlogController, :show, as: :post
    get "/courses", CourseController, :index
    get "/about", AboutController, :index
    get "/sitemap.xml", SitemapController, :index
    get "/tags/:slug", TagController, :index
    resources "/in", SessionController, only: [:new, :create], as: :sign_in
    delete "/out", SessionController, :delete, as: :sign_out
  end

  scope "/admin", BlogWeb.Admin, as: :admin do
    pipe_through [:browser, :protected]

    get "/", DashboardController, :index
    resources "/posts", PostController, param: "titled_slug"
    get "/settings", SettingsController, :index
    resources "/tags", TagController, param: "slug"
    resources "/users", UserController
  end
end

lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :public_view
  import BlogWeb.Meta.AdminTitle

  alias Phoenix.{Controller, Naming}

  @doc """
  Returns `class_name` for a given connection if it matches any of the provided
  'matchers'. A 'matcher' could be a string representation of a controller/
  action combo, or it could be a regular expression.
  """
  def active_class(conn, matchers, class_name \\ "is-active")

  def active_class(conn, matchers, class_name) when is_binary(matchers),
    do: active_class(conn, [matchers], class_name)

  def active_class(conn, matchers, class_name) when is_list(matchers) do
    active_id = controller_action_combo(conn)

    if Enum.any?(matchers, fn x ->
         matcher = if Regex.regex?(x), do: x, else: ~r/#{x}/
         String.match?(active_id, matcher)
       end) do
      class_name
    end
  end

  defp controller_name(conn),
    do: Controller.controller_module(conn) |> Naming.resource_name("Controller")

  defp controller_action_combo(conn),
    do: [controller_name(conn), action_name(conn)] |> Enum.join("-")

  defp controller_action_combo_matches?(conn, list) when is_list(list) do
    combo = controller_action_combo(conn)
    Enum.any?(list, &(&1 == combo))
  end

  defp action_name(conn), do: Controller.action_name(conn)
end

lib/blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#502e71" />
    <meta property="og:url" content="https://www.hansjhoffman.dev" />
    <meta property="og:title" content="" />
    <meta property="og:description" content="" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="<%= Routes.static_path(@conn, "/images/logo.png") %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="640" />
    <meta name="twitter:site" content="https://www.hansjhoffman.dev" />
    <meta name="twitter:card" content="" />
    <meta name="twitter:image" content="<%= Routes.static_path(@conn, "/images/logo.png") %>" />

    <title>Blog · Hans Hoffman</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i&display=swap">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
    <link rel="alternate" href="/rss.xml" type="application/rss+xml" />
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/manifest.json") %>" />
  </head>
  
  <body>
    <header class="ds-header">
      
      <nav class="ds-nav" role="navigation">
      <img src="<%= Routes.static_path(@conn, "/images/logo.svg") %>" class="ds-header__brand" />
        <ul class="ds-nav__links">
          <%= if @current_user do %>
            <li>
              <%= link "Admin", to: Routes.admin_dashboard_path(@conn, :index), class: "ds-heading-5 ds-nav__link" %>
            </li>
          <% end %>
          <li>
            <%= link "About", to: Routes.about_path(@conn, :index), class: "ds-heading-5 ds-nav__link #{active_class(@conn, "about", "ds-nav__link--active")}" %>
          </li>
          <li>
            <%= link "Portfolio", to: Routes.portfolio_path(@conn, :index), class: "ds-heading-5 ds-nav__link #{active_class(@conn, "portfolio", "ds-nav__link--active")}" %>
          </li>
          <li>
            <%= link "Blog", to: Routes.blog_path(@conn, :index), class: "ds-heading-5 ds-nav__link #{active_class(@conn, "blog", "ds-nav__link--active")}" %>
          </li>
          <li>
            <%= link "Courses", to: Routes.course_path(@conn, :index), class: "ds-heading-5 ds-nav__link #{active_class(@conn, "course", "ds-nav__link--active")}" %>
          </li>
        </ul>
        <div class="ds-mobile-nav">
          <span />
          <span />
          <span />
          <span />
        </div>
      </nav>
      <div class="ds-theme-dropdown">
        <button class="ds-btn__dropdown" aria-label="theme switcher"></button>
        <div class="ds-theme-dropdown__content">
          <span onclick="alert('light')">Light</span>
          <span onclick="setTheme('dark')">Dark</span>
          <span onclick="setTheme('solarized-light')">Solarized Light</span>
          <span onclick="setTheme('solarized-dark')">Solarized Dark</span>
        </div>
      </div>
    </header>
    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer class="ds-footer">
      <div class="ds-caption">Made with <a href="https://phoenixframework.org/" class="ds-pretty-link">Elixir + Phoenix</a> & <a href="https://elm-lang.org/" class="ds-pretty-link">Elm</a></div>
    </footer>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/blog_web/templates/layout/protected.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= admin_page_title(assigns) %></title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700" />
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/admin.css") %>" />
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/favicon-32x32.png") %>" />
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/favicon-16x16.png") %>" />
  </head>

  <body>
    <header>
      <nav class="ds-primary-nav" role="navigation">
        <div class="ds-logo__container">
          <%= link to: Routes.blog_path(@conn, :index) do %>
            <img src="<%= Routes.static_path(@conn, "/images/logo.svg") %>" class="ds-logo" alt="logo" />
          <% end %>
        </div>
        <h6 class="ds-primary-nav__label">Manage</h6>
        <ul>
          <li>
            <%= link to: Routes.admin_dashboard_path(@conn, :index), class: "ds-primary-nav__link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="ds-social__icon" viewBox="0 0 24 24" version="1.1">
                <g fill="none">
                  <polygon points="0 0 24 0 24 24 0 24"></polygon>
                  <path d="m12.934 16.072l6.4264-5.116 0.15816-0.12524c0.64947-0.51428 0.75906-1.4577 0.24477-2.1072-0.07121-0.089929-0.1525-0.17139-0.24228-0.24279l-6.587-5.2387c-0.54657-0.43469-1.3208-0.43469-1.8674 0l-6.5915 5.2423c-0.64837 0.51566-0.75596 1.4593-0.2403 2.1077 0.070471 0.088608 0.15075 0.16895 0.23929 0.2395l0.15617 0.12442 6.4359 5.1166c0.54677 0.43469 1.3212 0.43443 1.8677-6.178e-4z" fill="currentColor" />
                  <path d="m11.056 18.671l-5.7204-4.5478c-0.39039-0.31036-0.95846-0.24549-1.2688 0.1449-0.0023872 0.0030027-0.0047552 0.0060207-0.007104 0.0090536-0.30743 0.39698-0.23483 0.96801 0.16215 1.2754 0.0014393 0.0011146 0.002882 0.0022249 0.0043279 0.0033309l6.8608 5.2475c0.5378 0.41133 1.2845 0.4114 1.8224 1.667e-4l6.8582-5.2435c0.40154-0.307 0.47818-0.88139 0.17118-1.2829-0.0013124-0.0017165-0.0026308-0.0034283-0.0039553-0.0051355-0.30831-0.39738-0.88038-0.46959-1.2778-0.16128-0.0028877 0.0022405-0.0057619 0.0044982-0.0086225 0.0067733l-5.7251 4.5533c-0.54648 0.43463-1.3206 0.4347-1.8671 1.763e-4z" fill="currentColor" opacity=".3" />
                </g>
              </svg>
              Dashboard
            <% end %>
          </li>
          <li>
            <%= link to: Routes.admin_user_path(@conn, :index), class: "ds-primary-nav__link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="ds-social__icon" viewBox="0 0 24 24" version="1.1">
                <g fill="none">
                  <polygon points="0 0 24 0 24 24 0 24" />
                  <path d="m18 14c-1.6569 0-3-1.3431-3-3 0-1.6569 1.3431-3 3-3s3 1.3431 3 3c0 1.6569-1.3431 3-3 3zm-9-3c-2.2091 0-4-1.7909-4-4s1.7909-4 4-4 4 1.7909 4 4-1.7909 4-4 4z" fill="currentColor" fill-rule="nonzero" opacity=".3" />
                  <path d="m17.601 15.001c3.4065 0.037236 6.188 1.7595 6.3973 5.3994 0.0084309 0.14661 0 0.6-0.54254 0.6h-3.8559c0-2.2509-0.74371-4.3282-1.9988-5.9994zm-17.601 5.1986c0.38761-4.7727 4.2613-7.1992 8.9827-7.1992 4.7879 0 8.7215 2.2932 9.0146 7.2 0.011674 0.19547 0 0.8-0.75121 0.8h-16.519c-0.25079 0-0.74796-0.54082-0.72685-0.80079z" fill="currentColor" fill-rule="nonzero" />
                </g>
              </svg>
              Staff
            <% end %>
          </li>
        </ul>
        <h6 class="ds-primary-nav__label">CMS</h6>
        <ul>
          <li>
            <%= link to: Routes.admin_post_path(@conn, :index), class: "ds-primary-nav__link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="ds-social__icon" viewBox="0 0 24 24" version="1.1">
                <g fill="none">
                  <rect width="24" height="24" />
                  <path d="m3 4h17c0.55228 0 1 0.44772 1 1v2c0 0.55228-0.44772 1-1 1h-17c-0.55228 0-1-0.44772-1-1v-2c0-0.55228 0.44772-1 1-1zm0 6h10c0.55228 0 1 0.44772 1 1v2c0 0.55228-0.44772 1-1 1h-10c-0.55228 0-1-0.44772-1-1v-2c0-0.55228 0.44772-1 1-1zm0 6h10c0.55228 0 1 0.44772 1 1v2c0 0.55228-0.44772 1-1 1h-10c-0.55228 0-1-0.44772-1-1v-2c0-0.55228 0.44772-1 1-1z" fill="currentColor" />
                  <rect x="16" y="10" width="5" height="10" rx="1" fill="currentColor" opacity=".3" />
                </g>
              </svg>
              Posts
            <% end %>
          </li>
          <li>
            <%= link to: Routes.admin_tag_path(@conn, :index), class: "ds-primary-nav__link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="ds-social__icon" viewBox="0 0 24 24" version="1.1">
                <g fill="none" fill-rule="evenodd">
                  <polygon points="0 0 24 0 24 24 0 24" />
                  <path d="m3.5227 14.029c-0.69694-0.7011-0.69694-1.8334 0-2.5345l8.0901-7.9537c0.33618-0.33051 0.78875-0.51572 1.2602-0.51572h6.4545c0.99274 0 1.7975 0.80478 1.7975 1.7975v6.436c0 0.48236-0.19387 0.94448-0.53801 1.2825l-8.0766 7.932c-0.33716 0.33753-0.79467 0.52719-1.2717 0.52719s-0.93459-0.18966-1.2717-0.52719l-6.4441-6.4441zm13.408-5.0122c0.99274 0 1.7975-0.80478 1.7975-1.7975s-0.80478-1.7975-1.7975-1.7975-1.7975 0.80478-1.7975 1.7975 0.80478 1.7975 1.7975 1.7975z" fill="currentColor" fill-rule="nonzero" />
                </g>
              </svg>
              Tags
            <% end %>
          </li>
        </ul>
        <h6 class="ds-primary-nav__label">SETTINGS</h6>
        <ul>
          <li>
            <%= link to: Routes.admin_settings_path(@conn, :index), class: "ds-primary-nav__link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="ds-social__icon" viewBox="0 0 24 24" version="1.1">
                <g fill="none" fill-rule="evenodd">
                  <rect width="24" height="24" />
                  <path d="m7 3h10c2.2091 0 4 1.7909 4 4s-1.7909 4-4 4h-10c-2.2091 0-4-1.7909-4-4s1.7909-4 4-4zm0 6c1.1046 0 2-0.89543 2-2s-0.89543-2-2-2-2 0.89543-2 2 0.89543 2 2 2z" fill="currentColor" />
                  <path d="m7 13h10c2.2091 0 4 1.7909 4 4s-1.7909 4-4 4h-10c-2.2091 0-4-1.7909-4-4s1.7909-4 4-4zm10 6c1.1046 0 2-0.89543 2-2s-0.89543-2-2-2-2 0.89543-2 2 0.89543 2 2 2z" fill="currentColor" opacity=".3" />
                </g>
              </svg>
            General
            <% end %>
          </li>
        </ul>
      </nav>
    </header>
    <main role="main">
      <div class="ds-topbar">
        <%= if @current_user do %>
          <span>Hello <%= @current_user.handle %></span>
          <%= link "Log out", to: Routes.sign_out_path(@conn, :delete), method: :delete %>
        <% end %>
      </div>
      <section>
        <%= render @view_module, @view_template, assigns %>
      </section>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>